name: simpleflutterapp
description: Simple App with Alan integration sample
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alan_voice: 2.0.7
  app_usage: ^2.0.0
  cupertino_icons: ^0.1.2
  google_fonts: ^2.1.0
  velocity_x: ^3.2.0
  flutter_svg: ^0.19.3
  hexcolor: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.svg
    - assets/logo.png
    - assets/ava.jpg
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Viaoda Libre
      fonts:
        - asset: fonts/ViaodaLibre-Regular.ttf
          weight: 700
